#!/bin/sh

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@netkeeper-interception[-1]
	add ucitrack netkeeper-interception
	set ucitrack.@netkeeper-interception[-1].init="netkeeper-interception"
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
